services:
  db:
    image: postgres:latest
    container_name: go_scraper_db
    restart: always
    environment:
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_pass
      POSTGRES_DB: scraper_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations  

volumes:
  postgres_data: